language: c

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
     - pip install --user cpp-coveralls

script:
    - make
    - ./test

after_success:
    - coveralls --exclude lib --exclude tests --exclude test --gcov-options '\-lp'
