#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "uriparse.h"


int main(int argc, const char *argv[]) {
    struct uri uri = {0};
    int rc = 0;

    printf("case 1\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 2\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 3\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 4\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 5\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 6\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 7\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 8\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 9\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 10\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 11\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 12\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 13\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 14\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 15\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 16\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@localhost", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 17\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 18\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 19\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 20\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 21\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 22\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 23\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 24\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 25\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 26\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 27\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 28\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 29\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 30\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 31\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 32\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@127.0.0.1", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 33\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 34\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 35\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 36\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 37\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 38\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 39\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 40\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 41\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 42\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 43\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 44\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 45\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 46\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 47\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 48\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root:e4D8F6z3f2b1@[::1]", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.passwd));
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 49\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 50\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 51\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 52\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 53\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 54\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 55\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 56\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 57\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 58\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 59\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 60\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 61\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 62\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 63\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 64\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@localhost", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 65\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 66\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 67\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 68\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 69\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 70\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 71\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 72\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 73\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 74\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 75\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 76\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 77\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 78\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 79\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 80\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@127.0.0.1", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 81\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 82\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 83\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 84\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 85\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 86\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 87\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 88\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 89\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 90\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 91\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 92\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 93\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 94\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 95\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 96\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://root@[::1]", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.user));
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 97\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 98\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 99\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 100\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 101\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 102\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 103\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 104\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 105\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 106\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 107\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 108\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 109\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 110\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 111\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 112\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://localhost", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 113\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 114\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 115\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 116\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 117\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 118\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 119\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 120\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 121\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 122\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 123\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 124\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 125\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 126\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 127\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 128\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://127.0.0.1", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 129\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 130\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 131\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 132\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 133\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 134\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 135\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 136\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]:3306", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 137\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 138\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 139\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 140\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 141\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 142\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 143\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 144\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql://[::1]", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(0 == strcmp("[::1]", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 145\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("unix:///var/run/docker.sock", &uri);
    assert(0 == rc);
    assert(0 == strcmp("unix", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(0 == strcmp("/var/run/docker.sock", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 146\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:/account?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 147\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:/account?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 148\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:/account#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 149\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:/account", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(0 == strcmp("/account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 150\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:?charset=utf8mb4#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 151\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:?charset=utf8mb4", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 152\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:#debug", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 153\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:", &uri);
    assert(0 == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 154\n");
    bzero(&uri, sizeof(struct uri));
    rc = uriparse("mysql:root:e4D8F6z3f2b1@localhost:3306/account?charset=utf8mb4#debug", &uri);
    assert(EXIT_FAILURE == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.user);
    assert(NULL == uri.passwd);
    assert(NULL == uri.host);
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    return EXIT_SUCCESS;
}
